### PR TITLE
Create jer_dd_mupreva

### PR DESCRIPTION
**Pull request by pricua**
table jer_dd for tld mupreva  for add to official ontology

### CODE REVIEW

**Comment by pricua** [comment]
I have added in dedalo / install / import / ontology /
the jer_dd_mupreva and matrix_descriptors_dd_mupreva files with the updated ontology for the mupreva tld to be incorporated into the official ontology.
It's the first time I've done it so I don't know if it's in the correct format. If there is something wrong they indicate it to me and I upload it again corrected.

Thanks

**Comment by renderpci** [comment]
Hi Pricua

A question
Does the mupreva tld has "final" version of changes? 
In other words; Did you test it your changes before pull request?

Thanks.

**Comment by pricua** [comment]
Hi renderpci,

Yes, the changes were first tested in a development environment and later they were implemented in the production environment where they are currently being used and from where the files were exported.

If you need any further clarification you tell me.

**Comment by devpacdd** [comment]
Hi pricua

I can't validate current files because the format is not compatible with direct PostgreSQL import (the main idea is to import files directly without making changes to them).
Please use a command like this:

`psql my_db_name -c "\copy (SELECT parent, dato, tipo, lang FROM matrix_descriptors_dd WHERE parent LIKE 'mupreva%' ORDER BY "id" ASC) TO 'matrix_descriptors_dd_mupreva.copy' " ;`

Thanks.

**Comment by pricua** [comment]
Hi devpacdd,

I added new files jer_dd_mupreva.copy and matrix_descriptors_dd_mupreva.copy generated with commands

psql dedalo4_mupreva -c "\copy (SELECT \"terminoID\",parent,modelo,esmodelo,esdescriptor,visible,norden,tld,traducible,relaciones,propiedades FROM jer_dd WHERE tld LIKE 'mupreva' ORDER BY "id" ASC) TO 'jer_dd_mupreva.copy' "

psql dedalo4_mupreva  -c "\copy (SELECT parent, dato, tipo, lang FROM matrix_descriptors_dd WHERE parent like 'mupreva%' ORDER BY "id" ASC) TO 'matrix_descriptors_dd_mupreva.copy' "

I hope that is correct. If it doesn't work tell me please.

Thanks

**Pull request merged**
